/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Payload =
  | {
      http: HttpPayload;
    }
  | {
      messageQueue: MessageQueuePayload;
    }
  | {
      event: EventPayload;
    };
export type Subscriber = {
  kafka: KafkaSubscriber;
};

/**
 * Payload represent a HTTP request
 */
export interface HttpPayload {
  /**
   * The identity context of API Gateway
   */
  apiGatewayIdentityContext: DataSourceIdentityContext;
  /**
   * The identity context of API
   */
  apiIdentityContext: DataSourceIdentityContext;
  /**
   * A base64-encoded string
   */
  body: number[];
  headers: {
    [k: string]: unknown;
  };
  host: string;
  method: string;
  path: string;
  query: string;
  requestId: string;
  scheme: string;
  version: "HTTP/0.9" | "HTTP/1.0" | "HTTP/1.1" | "HTTP/2.0" | "HTTP/3.0";
  [k: string]: unknown;
}
export interface DataSourceIdentityContext {
  /**
   * Saffron internal id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  [k: string]: unknown;
}
/**
 * Payload represents a Message Queue Message
 */
export interface MessageQueuePayload {
  clientIdentityContext: DataSourceIdentityContext;
  data: number[];
  subscriber: Subscriber;
  [k: string]: unknown;
}
export interface KafkaSubscriber {
  brokers: string[];
  groupId: string;
  offset: number;
  partition: number;
  topic: string;
  [k: string]: unknown;
}
/**
 * Payload represent an Event
 */
export interface EventPayload {
  [k: string]: unknown;
}
